---
language: scala
script: >
  sbt ++$TRAVIS_SCALA_VERSION check &&
  sbt ++$TRAVIS_SCALA_VERSION test

jdk:
  - openjdk8

matrix:
  include:
    - scala: 2.12.9
    - scala: 2.11.12

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier
